---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: ubuntu:12.04
  - name: ubuntu-14.04
    driver_config:
      image: ubuntu:14.04
    attributes:
      td_agent:
        version: 2
  - name: centos-6.6
    driver_config:
      image: centos:centos6
  - name: debian-7.8
    driver_config:
      image: debian:7.8

suites:
  - name: default
    run_list:
      - recipe[td-agent::default]
    attributes:
      td_agent:
        includes: true
#       plugins:
#         - forest

  - name: td-agent-1x
    run_list:
      - recipe[td-agent::default]
    attributes:
      td_agent:
        version: 1
    excludes:
      - ubuntu-14.04

  - name: lwrp
    run_list:
      - recipe[smoke::default]
