---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  log_level: info
  deprecations_as_errors: true

platforms:
  - name: ubuntu-xenial
    driver_config:
      platform: ubuntu
      image: ubuntu:16.04
  - name: centos-centos6
    driver_config:
      platform: centos
      image: centos:centos6
  - name: centos-centos7
    driver_config:
      platform: centos
      image: centos:centos7

suites:
# - name: 1x-chef12
#   attributes:
#     td_agent:
#       version: 1
#   driver_config:
#     require_chef_omnibus: 12.21.3
#   excludes:
#     - ubuntu-xenial-chef12
#   run_list:
#     - recipe[smoke::default]
  - name: 2x-chef12
    attributes:
      td_agent:
        version: 2.2.0
    driver_config:
      require_chef_omnibus: 12.21.3
    run_list:
      - recipe[smoke::default]
  - name: 3x-chef12
    attributes:
      td_agent:
        version: 3.1.0
    driver_config:
      require_chef_omnibus: 12.21.3
    run_list:
      - recipe[smoke::default]
  - name: 2x-chef13
    attributes:
      td_agent:
        version: 2.2.0
    driver_config:
      require_chef_omnibus: 13.2.20
    run_list:
      - recipe[smoke::default]
  - name: 3x-chef13
    attributes:
      td_agent:
        version: 3.1.0
    driver_config:
      require_chef_omnibus: 13.2.20
    run_list:
      - recipe[smoke::default]
